# Generated by Django 4.0.5 on 2022-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.CharField(choices=[('문학', '문학'), ('자기계발', '자기계발'), ('인문', '인문'), ('정치/사회', '정치/사회'), ('예술', '예술'), ('과학', '과학'), ('기술/IT', '기술/IT'), ('자율', '자율')], max_length=64),
        ),
    ]
