# Generated by Django 4.0.5 on 2022-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, unique=True, verbose_name='닉네임'),
        ),
    ]
