# Generated by Django 4.0.5 on 2022-06-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
