# Generated by Django 4.0.5 on 2022-06-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Hi', max_length=32, verbose_name='닉네임'),
        ),
    ]
