# Generated by Django 4.0.5 on 2022-06-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='', verbose_name='프로필 사진'),
        ),
    ]
