# Generated by Django 4.0.5 on 2022-06-22 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0004_alter_book_table'),
        ('user', '0007_remove_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_report.book')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scrap',
            },
        ),
    ]
