# Generated by Django 4.0.5 on 2022-06-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_mail_receiver'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mail',
            table='mail',
        ),
    ]
