# Generated by Django 4.0.5 on 2022-06-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200, verbose_name='독후감 제목')),
                ('book_name', models.CharField(max_length=200, verbose_name='책 제목')),
                ('book_writer', models.CharField(max_length=200, verbose_name='책 글쓴이')),
                ('category', models.CharField(max_length=200, verbose_name='책 검색')),
                ('content', models.TextField(help_text='독후감을 적어주세요', verbose_name='독후감 내용')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
