# Generated by Django 4.0.5 on 2022-06-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200, verbose_name='독후감 제목')),
                ('book_name', models.CharField(max_length=200, verbose_name='책 제목')),
                ('category', models.CharField(max_length=200, verbose_name='책 카테고리')),
                ('content', models.TextField(help_text='독후감을 적어주세요', verbose_name='독후감 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'BookReport',
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_report', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_report.bookreport')),
            ],
            options={
                'db_table': 'scrap',
            },
        ),
    ]
