# Generated by Django 4.0.5 on 2022-06-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_writer',
            new_name='book_author',
        ),
    ]
