# Generated by Django 4.0.5 on 2022-06-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreport',
            old_name='category',
            new_name='book_category',
        ),
        migrations.RenameField(
            model_name='bookreport',
            old_name='picture',
            new_name='book_img',
        ),
    ]
