# Generated by Django 4.0.5 on 2022-06-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
    ]
