# Generated by Django 4.0.5 on 2022-06-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0002_rename_book_writer_book_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
