# Generated by Django 4.0.5 on 2022-06-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0003_book_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookReport',
        ),
        migrations.AlterModelTable(
            name='bookreport',
            table='BookReport',
        ),
    ]
