# Generated by Django 4.0.5 on 2022-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0004_rename_book_bookreport_alter_bookreport_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreport',
            name='book_author',
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='category',
            field=models.CharField(max_length=200, verbose_name='책 카테고리'),
        ),
    ]
