# Generated by Django 4.0.5 on 2022-06-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0005_alter_comment_created_at'),
        ('book_report', '0005_bookreport_like_alter_comment_created_at'),
    ]

    operations = [
    ]
