# Generated by Django 4.0.5 on 2022-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0006_merge_20220625_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreport',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes_counter'),
        ),
    ]
