# Generated by Django 4.0.5 on 2022-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0007_bookreport_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreport',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='book_report_images'),
        ),
    ]
