# Generated by Django 4.0.5 on 2022-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0007_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreport',
            name='if_scrap',
            field=models.BooleanField(default=False),
        ),
    ]
