# Generated by Django 4.0.5 on 2022-06-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0006_merge_20220625_1439'),
        ('book_report', '0007_bookreport_likes'),
    ]

    operations = [
    ]
