# Generated by Django 4.0.5 on 2022-06-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0008_bookreport_if_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreport',
            name='if_scrap',
        ),
    ]
