# Generated by Django 4.0.5 on 2022-06-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0008_merge_0006_merge_20220625_1439_0007_bookreport_likes'),
        ('book_report', '0009_alter_bookreport_image_upload'),
    ]

    operations = [
    ]
