# Generated by Django 4.0.5 on 2022-06-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0012_remove_bookreport_profile_book_profilebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileBook',
        ),
    ]
