# Generated by Django 4.0.5 on 2022-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0014_scrap_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=70, verbose_name='content'),
        ),
    ]
