# Generated by Django 4.0.5 on 2022-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0016_alter_bookreport_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='book_report_images'),
        ),
    ]
