# Generated by Django 4.0.5 on 2022-06-23 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, verbose_name='북클럽명')),
                ('image', models.CharField(max_length=100, verbose_name='북 클럽 이미지')),
                ('category', models.CharField(choices=[('문학', '문학'), ('경제/경영', '경제/경영'), ('자기계발', '자기계발'), ('인문', '인문'), ('정치/사회', '정치/사회'), ('예술', '예술'), ('과학', '과학'), ('기술/IT', '기술/IT')], max_length=64)),
                ('member_total', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)])),
                ('member_cnt', models.IntegerField(default=1)),
                ('description', models.TextField(help_text='소모임 소개글을 적어주세요.', null=True, verbose_name='소모임 소개')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='줌 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'book_club',
            },
        ),
        migrations.CreateModel(
            name='BookClubBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='책 제목')),
                ('book_author', models.CharField(max_length=200, verbose_name='책 글쓴이')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='책 이미지')),
            ],
            options={
                'db_table': 'club_book',
            },
        ),
        migrations.CreateModel(
            name='BookClubVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='투표 주제')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclub', verbose_name='소모임 ID')),
            ],
            options={
                'db_table': 'vote',
            },
        ),
        migrations.CreateModel(
            name='VoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='투표 상세 내용을 적어주세요.', verbose_name='투표 상세 내용')),
                ('vote_cnt', models.IntegerField(default=0)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclubvote', verbose_name='투표')),
            ],
            options={
                'db_table': 'vote_detail',
            },
        ),
        migrations.CreateModel(
            name='BookClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEMBER', 'MEMBER'), ('CANDIDATE', 'CANDIDATE'), ('OWNER', 'OWNER'), ('INVITE', 'INVITE')], default='CANDIDATE', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclub', verbose_name='소모임 ID')),
            ],
            options={
                'db_table': 'club_member',
            },
        ),
    ]
