# Generated by Django 4.0.5 on 2022-06-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookclub',
            old_name='owner',
            new_name='user_id',
        ),
    ]
