# Generated by Django 4.0.5 on 2022-06-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='투표 상세 내용을 적어주세요.', verbose_name='투표 상세 내용')),
                ('vote_cnt', models.IntegerField(default=0)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclubvote', verbose_name='투표')),
            ],
            options={
                'db_table': 'vote_detail',
            },
        ),
    ]
