# Generated by Django 4.0.5 on 2022-06-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0002_rename_owner_bookclub_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookclub',
            old_name='user_id',
            new_name='user',
        ),
    ]
