# Generated by Django 4.0.5 on 2022-06-22 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_club', '0002_votedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEMBER', 'MEMBER'), ('CANDIDATE', 'CANDIDATE'), ('OWNER', 'OWNER'), ('INVITE', 'INVITE')], max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclub', verbose_name='소모임 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 ID')),
            ],
            options={
                'db_table': 'club_member',
            },
        ),
    ]
