# Generated by Django 4.0.5 on 2022-06-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclubmember', verbose_name='멤버 ID')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.votedetail', verbose_name='투표 ID')),
            ],
            options={
                'db_table': 'vote_check',
            },
        ),
    ]
