# Generated by Django 4.0.5 on 2022-06-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0003_rename_user_id_bookclub_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookclub',
            old_name='user',
            new_name='owner',
        ),
    ]
