# Generated by Django 4.0.5 on 2022-06-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0003_bookclubmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclubmember',
            name='type',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('CANDIDATE', 'CANDIDATE'), ('OWNER', 'OWNER'), ('INVITE', 'INVITE')], default='CANDIDATE', max_length=20),
        ),
    ]
