# Generated by Django 4.0.5 on 2022-06-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0003_rename_image_book_book_img_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='category',
            field=models.CharField(choices=[('문학', '문학'), ('경제/경영', '경제/경영'), ('자기계발', '자기계발'), ('인문', '인문'), ('정치/사회', '정치/사회'), ('예술', '예술'), ('과학', '과학'), ('기술/IT', '기술/IT'), ('자율', '자율')], max_length=64),
        ),
    ]
