# Generated by Django 4.0.5 on 2022-06-29 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_club', '0003_votecheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votecheck',
            old_name='vote',
            new_name='vote_detail',
        ),
        migrations.RemoveField(
            model_name='votecheck',
            name='member',
        ),
        migrations.AddField(
            model_name='votecheck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 ID'),
            preserve_default=False,
        ),
    ]
