# Generated by Django 4.0.5 on 2022-06-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0004_book_active_alter_bookclub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
