# Generated by Django 4.0.5 on 2022-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0004_rename_user_bookclub_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='줌 링크'),
        ),
    ]
