# Generated by Django 4.0.5 on 2022-06-29 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0004_rename_vote_votecheck_vote_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votecheck',
            name='vote_detail',
        ),
        migrations.AddField(
            model_name='votecheck',
            name='vote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclubvote', verbose_name='투표 ID'),
            preserve_default=False,
        ),
    ]
