# Generated by Django 4.0.5 on 2022-06-22 06:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0005_alter_bookclub_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='description',
            field=models.TextField(help_text='소모임 소개글을 적어주세요.', null=True, verbose_name='소모임 소개'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='member_total',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='club_name',
            field=models.CharField(max_length=50, verbose_name='북클럽명'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='image',
            field=models.CharField(max_length=100, verbose_name='북 클럽 이미지'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='member_cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BookClubVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='투표 제목')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_club.bookclub', verbose_name='투표')),
            ],
            options={
                'db_table': 'vote',
            },
        ),
    ]
