# Generated by Django 4.0.5 on 2022-06-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0004_alter_bookclub_category'),
        ('book_club', '0006_book_created_at'),
    ]

    operations = [
    ]
