# Generated by Django 4.0.5 on 2022-06-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0010_bookclubvote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
