# Generated by Django 4.0.5 on 2022-06-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0011_bookclub_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
